
trigger:

  branches:

    include:

      - main



pool:

  name: 'self-hosted-linux-agents' # this is the name of the pool where the pipeline will run

  demands:

    - agent.name -equals first-agent # this is the name of the agent where the pipeline will run





variables:

- template: variables.yml



stages:

- stage: CheckoutAndAuthenticate

  displayName: 'Checkout and Authenticate'

  jobs:

  - job: Authenticate

    displayName: 'Authenticate to Azure'

    steps:

    - checkout: self

      displayName: 'Checkout my code'

    

    - script: |

        az --version

        az bicep version

      displayName: 'Validate azure CLI and Bicep installation'



    - script: |

        echo "Setting up Azure CLI..."

        az login --service-principal -u $(APPLICATION_ID) -p $(APPLICATION_SECRET) --tenant $(TENANT_ID)

        az account set --subscription $(SUBSCRIPTION_ID)

      displayName: 'Azure CLI Setup - Authenticate to Azure'

      

# For the sake of learning, we deploy using complete mode

# This will also delete any resources not defined in the Bicep template to together with the resources defined in the template

- stage: DeployInfrastructure

  displayName: 'Deploy Infrastructure'

  dependsOn: CheckoutAndAuthenticate

  jobs:

  - job: DeployInfrastructure

    displayName: 'Deploy Infrastructure'

    steps:

    - script: |

        echo "Deploying Bicep Template..."

        az deployment group create \

          --mode Complete \

          --resource-group $(RG) \

          --template-file deployments/bicep/main.bicep \

          --parameters deployments/bicep/main.bicepparam \

          --name "infrastructure-$(Build.BuildId)"

      displayName: 'Deploy Bicep Template'



    - script: |

        echo "✅ Infrastructure deployed successfully!"

          

        # Show created resources

        az resource list \

          --resource-group $(RG) \

          --query "[].{Name:name, Type:type, Location:location}" \

          --output table

      displayName: 'Show Deployment Results'

